# Backend deployment configuration for Fly.io
app = "klubbspel-backend"
primary_region = "arn"  # Stockholm region

[build]
  dockerfile = "Dockerfile.backend"

[env]
  GO_ENV = "production"
  GRPC_ADDR = ":9090"
  HTTP_ADDR = ":8080"
  SITE_ADDR = ":8081"
  DEFAULT_LOCALE = "sv"

# MongoDB Atlas connection will be set via secrets:
# fly secrets set MONGO_URI="mongodb+srv://username:password@cluster.mongodb.net/pingis?retryWrites=true&w=majority"
# fly secrets set MONGO_DB="pingis"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.health]
    type = "http"
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/healthz"
    port = 8081
    timeout = "5s"

[[vm]]
  size = "shared-cpu-1x"
